/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appoyofamiliar.vista;

import appoyofamiliar.modelo.*;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author Jesús Durántez Prieto
 */
public class GestionarSalidasGrande extends javax.swing.JFrame {
    
    private Usuario usuario;
    
    private static String[] cabecera = {"ACOMPAÑANTE", "DNI PACIENTE", "MEDICO", "ESPECIALIDAD", "CENTRO", "AREA", "DESCRIPCION", "TRANSPORTE", "FECHAINICIO", "FECHAFIN"};
    private static DefaultTableModel dtm;
    
    /**
     * Creates new form GestionarSalidasGrande
     */
    public GestionarSalidasGrande() {
        initComponents();
    }
    
    public GestionarSalidasGrande(Usuario usr) {
        initComponents();
        this.usuario = usr;
        dtm = new DefaultTableModel(ConjuntoSalida.instancia().obtenerDatosTablaGrandePendientes(usuario),cabecera);
        tablaSalidas.setModel(dtm);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesSalidas = new javax.swing.ButtonGroup();
        botonCerrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSalidas = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        salidasPendientes = new javax.swing.JRadioButton();
        salidasRealizadas = new javax.swing.JRadioButton();
        todasLasSalidas = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GESTIONAR SALIDAS");

        botonCerrar.setText("<html>CERRAR<br/>SALIDA</html>");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        tablaSalidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaSalidas);

        jButton6.setText("SALIR");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTION DE SALIDAS");

        opcionesSalidas.add(salidasPendientes);
        salidasPendientes.setSelected(true);
        salidasPendientes.setText("Salidas pendientes");
        salidasPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidasPendientesActionPerformed(evt);
            }
        });

        opcionesSalidas.add(salidasRealizadas);
        salidasRealizadas.setText("Salidas realizadas");
        salidasRealizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidasRealizadasActionPerformed(evt);
            }
        });

        opcionesSalidas.add(todasLasSalidas);
        todasLasSalidas.setText("Todas las Salidas");
        todasLasSalidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todasLasSalidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1126, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104)
                        .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(403, 403, 403)
                .addComponent(salidasPendientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(salidasRealizadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(todasLasSalidas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salidasPendientes)
                    .addComponent(salidasRealizadas)
                    .addComponent(todasLasSalidas))
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCerrar)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        int fila = tablaSalidas.getSelectedRow();
        if (fila < 0){
            JOptionPane.showMessageDialog(this, "Seleccione un elemento", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            String fechaFin = JOptionPane.showInputDialog((new JFrame("CERRAR SALIDA")), "Escriba la fecha yyyy-mm-dd");
            
            if (fechaFin == null){
                /*Si pulsamos en "Cancelar", devolverá null, debemos controlar
                este retorno lo primero, puesto que si le pedimos que haga el equals
                siendo null, saltan errores por todos lados...*/
            }else if (fechaFin.equals("") || fechaFin.equals("null")){
                JOptionPane.showMessageDialog(this, "La fecha no es válida", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                ConjuntoSalida.instancia().cerrarSalida(Integer.parseInt(tablaSalidas.getValueAt(fila, 0).toString()), fechaFin);
                tablaSalidas.clearSelection();
                if (salidasPendientes.isSelected()){
                    dtm = new DefaultTableModel(ConjuntoSalida.instancia().obtenerDatosTablaPreviaPendientes(),cabecera);
                } else if (salidasRealizadas.isSelected()){
                    dtm = new DefaultTableModel(ConjuntoSalida.instancia().obtenerDatosTablaPreviaRealizadas(),cabecera);
                } else {
                    dtm = new DefaultTableModel(ConjuntoSalida.instancia().obtenerDatosTablaPrevia(),cabecera);
                }
                tablaSalidas.setModel(dtm);
            }
        }
        
    }//GEN-LAST:event_botonCerrarActionPerformed

    private void salidasPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidasPendientesActionPerformed
        botonCerrar.setText("<html>CERRAR<br/>SALIDA</html>");
        dtm = new DefaultTableModel(ConjuntoSalida.instancia().obtenerDatosTablaGrandePendientes(usuario),cabecera);
        tablaSalidas.setModel(dtm);
    }//GEN-LAST:event_salidasPendientesActionPerformed

    private void salidasRealizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidasRealizadasActionPerformed
        botonCerrar.setText("<html>MODIFICAR<br/>HORA FIN</html>");
        dtm = new DefaultTableModel(ConjuntoSalida.instancia().obtenerDatosTablaGrandeRealizadas(usuario),cabecera);
        tablaSalidas.setModel(dtm);
    }//GEN-LAST:event_salidasRealizadasActionPerformed

    private void todasLasSalidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todasLasSalidasActionPerformed
        botonCerrar.setText("<html>MODIFICAR<br/>HORA FIN</html>");
        dtm = new DefaultTableModel(ConjuntoSalida.instancia().obtenerDatosTablaGrande(usuario),cabecera);
        tablaSalidas.setModel(dtm);
    }//GEN-LAST:event_todasLasSalidasActionPerformed

    public void cerrarSalida(String ff){
        //ConjuntoSalida.instancia().buscarSalida(e, p, ff);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarSalidasGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarSalidasGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarSalidasGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarSalidasGrande.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarSalidasGrande().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.ButtonGroup opcionesSalidas;
    private javax.swing.JRadioButton salidasPendientes;
    private javax.swing.JRadioButton salidasRealizadas;
    private javax.swing.JTable tablaSalidas;
    private javax.swing.JRadioButton todasLasSalidas;
    // End of variables declaration//GEN-END:variables
}
